# Generated by Django 5.2.5 on 2025-08-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='No comments'),
            preserve_default=False,
        ),
    ]
